src/Entity/GalleryImage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GalleryImageRepository")
 * @Vich\Uploadable
 */
class GalleryImage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ImageFileName;

    /**
     * @Vich\UploadableField(mapping="gallery_directory", fileNameProperty="image_file_name")
     * @var File
     * @Assert\Image(
     *     mimeTypes={"image/jpeg", "image/png", "image/webp"},
     *     mimeTypesMessage="Merci d'enregistrer une image au format webp, jpg ou png"
     * )
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImageFileName(): ?string
    {
        return $this->ImageFileName;
    }

    public function setImageFileName(?string $ImageFileName): GalleryImage
    {
        $this->ImageFileName = $ImageFileName;
        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile(File $ImageFileName = null)
    {
        $this->imageFile = $ImageFileName;
        if ($ImageFileName) {
            $this->updatedAt = new \DateTime('now');
        }
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     * @return GalleryImage
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }
}

src/Entity/Productor.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductorRepository")
 * @Vich\Uploadable
 */

class Productor
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @Vich\UploadableField(mapping="productors_directory", fileNameProperty="filename")
     * @var File
     * @Assert\Image(
     *     mimeTypes={"image/jpeg", "image/png", "image/webp"},
     *     mimeTypesMessage="Merci d'enregistrer une image au format webp, jpg ou png"
     * )
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $delivery;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $label;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="App\Entity\Contract", mappedBy="productor", cascade={"persist", "remove"})
     */
    private $contracts;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $image_description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     */
    private $position;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link;

    public function __construct()
    {
        $this->contracts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @param Contract $contract
     * @return Productor
     */
    public function addContract(Contract $contract): Productor
    {
        $contract->setProductor($this);
        $this->contracts[] = $contract;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getContracts()
    {
        return $this->contracts;
    }

    /**
     * @param Contract $contract
     * @return Productor
     */
    public function removeContract(Contract $contract): Productor
    {
        $this->contracts->removeElement($contract);

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getImageDescription(): ?string
    {
        return $this->image_description;
    }

    public function setImageDescription(string $image_description): self
    {
        $this->image_description = $image_description;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(?string $filename): Productor
    {
        $this->filename = $filename;
        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile(File $filename = null)
    {
        $this->imageFile = $filename;
        if ($filename) {
            $this->updatedAt = new \DateTime('now');
        }
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     * @return Productor
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    public function __toString(): ?string
    {
        return $this->getName();
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }
}

templates/pages/agenda.html.twig
{% extends 'base.html.twig' %}

{% block title "Retourn\'AMAP - agenda" %}

{% set active = 'agenda' %}

{% block body %}
	<section id='caldendar_page' class='container'>
		<div id='calendar'></div>
	</section>
{% endblock %}

templates/pages/amapj.html.twig
{% extends 'base.html.twig' %}

{% block title 'Retourn\'AMAP - AMAPJ' %}

{% set active = 'amapj' %}

{% block body %}
	<section id='amapj'>
		<h2>AMAPJ</h2>
		<p>Désormais pour commander auprès de nos producteurs, retournamap utilise AMAPJ<br/>Si vous êtes déjà ahérent voici le lien :
		</p>
		<a href='https://contrats.amapj.fr/b/retournac' target='_blank' class='btn' rel='noopener'>Mon espace AMAPJ</a>
		<p>Pour ceux qui souhaitent découvrir AMAPJ plus en détails, voici
			<a href='https://amapj.fr/docs_utilisateur_adherent.html' class='underline' target='_blank' rel='noopener'>le manuel de l'adhérent</a>
		</p>
	</section>
{% endblock %}

templates/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block title 'Retourn\'AMAP - contact' %}

{% set active = 'contact' %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}
	<section id='contact'>
		<h2 class='text-center my-4'>
			Venez nous rencontrer lors des distributions de Retourn'AMAP les jeudis soirs de 18h30 à 19h00, nous serons heureux de vous accueillir !
		</h2>
		<div class='grid'>
			<div class='form-container'>
				<article>
					<h5><img src='{{ asset('img/contact/email.svg') }}' alt='' aria-hidden='true'/>
						Nous écrire</h5>
					{{ form_start(form) }}
					{% for message in app.flashes('success')  %}
<p class='alert alert-success'>
	{{ message }}
</p>{% endfor %}{{ form_label(form.name, 'Nom / prénom', {'label_attr': {'class':'label-hidden'}}) }}{{ form_widget(form.name, {
                                attr:{
                                    placeholder: 'Nom / prénom'
                                }
                            }) }}{{ form_label(form.mail, 'Adresse mail', {'label_attr': {'class':'label-hidden'}}) }}{{ form_widget(form.mail, {
                                attr:{
                                    placeholder: 'Adresse mail'
                                }
                            }) }}{{ form_label(form.subject, 'Sujet', {'label_attr': {'class':'label-hidden'}}) }}{{ form_widget(form.subject, {
                                attr:{
                                    placeholder: 'Sujet'
                                }
                            }) }}{{ form_label(form.content, 'Message', {'label_attr': {'class':'label-hidden'}}) }}{{ form_widget(form.content, {
                                attr:{
                                    placeholder: 'Message'
                                }
                            }) }}{{ form_label(form.attachment, ' ', {'label_attr': {'class':'label-hidden'}}) }}{{ form_widget(form.attachment) }}<div class='form-end'>
{{ form_row(form.recaptcha) }}
{{ form_row(form.send) }}</div>{{ form_end(form) }}</article><aside><h5><img src='{{ asset('img/contact/place.svg') }}' alt='' aria-hidden='true'/>
Nous situer</h5><a href='https://www.g.page/retourn-amap?share' title='Voir le plan' target='_blank' rel="noopener">
<img src='{{ asset('img/contact/map.webp') }}' alt='carte localisation retournamap'/></a></aside></div><ul class='tools my-4'><li><img src='{{ asset('img/contact/phone.svg') }}' alt='' aria-hidden='true'/>&nbsp;<a href='tel:07.82.90.98.00' class='underline'>07.82.90.98.00</a></li><li><img src='{{ asset('img/contact/email.svg') }}' alt='' aria-hidden='true'/>&nbsp;<a href='mailto:retournamap@gmail.com' class='underline'>retournamap@gmail.com</a></li><li><img src='{{ asset('img/contact/facebook.svg') }}' alt='logo facebook' aria-hidden='true'/>&nbsp;<a href='https://www.facebook.com/RetournAMAP/' target='_blank' rel='noopener' class='underline'>@RetournAMAP</a></li><li><img src='{{ asset('img/contact/illiwap-logo.png') }}' alt='logo Illiwap' aria-hidden='true'/>&nbsp;<a href='https://station.illiwap.com/fr/public/france-nature-environnement-retournamap' target='_blank' rel='noopener' class='underline'>Station Illiwap</a></li></ul></div></section>{% endblock %}

templates/pages/explain.html.twig
{% extends 'base.html.twig' %}

{% block title 'Retourn\'AMAP - fonctionnement' %}

{% set active = 'explain' %}

{% block body %}
	<div class='section-divider' role='complementary' id='explain'>
		<section>
			<h2>Inscription</h2>
			<p>
				<strong>Pour adhérer, tout se passe en ligne via helloasso :</strong>
			</p>
			<ul class='btn-list'>
				<li>
					<a href='https://www.helloasso.com/associations/retourn-amap/adhesions/adhesion-annuelle' target="_blank" class='btn'>Adhérer à l'AMAP</a>
				</li>
			</ul>
		</section>
		<section class='container'>
			<h2>Fonctionnement des permanences</h2>
			<p>
				<strong>Les distributions ont lieu les jeudis soirs de 18h30 à 19h
					<a href='https://www.google.com/maps/place/La+Filature/@45.20166,4.039126,15z/data=!4m5!3m4!1s0x0:0xd3b753f697a3a251!8m2!3d45.2016604!4d4.0391256?hl=fr' target='_blank' rel='noopener' class='underline'>salle La Forge, à la Filature de Retournac.</a>
				</strong>
			</p>
			<p>
				<strong>Venez récupérer les paniers commandés pendant ces horaires de permanences !</strong>
			</p>
		</section>
		<section class='container'>
			<h2>Commander</h2>
			<article>
				<h5>Les contrats :</h5>
				<p>L’AMAP est facilitatrice de contact : elle met en lien des Paysans et des Amapiens. Le contrat
					                        encadre juridiquement le partenariat.</p>
				<p>
					<b>L’Amapien est libre de choisir le nombre de Paysans avec lequel il a des contrats, libre de choisir le
						                        contenu de ses paniers et la fréquence de ceux-ci.</b>
				</p>
				<p>
					<a href='{{ path('productors') }}' class='underline'>Ces contrats sont consultables sur le site</a>
					mais pour commander, demandez votre accès AMPAJ par mail à :
					<a href='mailto:retournamap@gmail.com' class='underline'>retournamap@gmail.com</a>
				</p>
				<p>Chez Retourn’AMAP, le renouvellement des contrats se déroule une fois par trimestre.</br> L’adhésion est de 12€ minimum pour un an.</p>
				<p>Le paiement des contrats s’effectue de la façon suivante :
					<b>paiement par chèque à chaque producteur lors du renouvellement des contrats.</b>
				</p>
			</article>
		</section>
		<section class='container'>
			<h2>Devenez un Amapien actif !</h2>
			<article>
				<h5>Pendant les permanences :</h5>
				<ul>
					<li>- Soyez présent tout au long de la permanence.</li>
					<li>- Aidez les producteurs et le bureau à installer la salle.</li>
					<li>- Aidez à la distribution des commandes.</li>
					<li>- Donnez un coup de main pour laisser la salle propre.</li>
				</ul>
				<br>
				<h5>Pour les commandes groupées à Meygalimenterre :</h5>
				<p>Les commandes groupées sont à aller chercher à l'espace culturel de St Julien Chapteuil.
					<br>
					Un roulement est mis en place pour assurer la bonne distribution à Retournac.</p>
			</article>
		</section>
	</div>
{% endblock %}

templates/pages/gallery.html.twig
{% extends 'base.html.twig' %}

{% block title 'Retourn\'AMAP - galerie' %}

{% set active = 'gallery' %}

{% block body %}
	<section id='scroll'>
		<h2>Galerie</h2>
		<div class='grid gallery' id='photos'>
			{% for image in images %}
				<a href='img/gallery/{{ image.imageFileName }}' data-lightbox='mygallery' data-title='{{ image.description }}' class='img-link'>
					<img src='img/gallery/{{ image.imageFileName }}' alt='{{ image.description }}' title='{{ image.description }}'>
				</a>
			{% endfor %}
		</div>
	</section>
{% endblock %}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block title "Retourn'Amap - amap de retournac" %}

{% set active = 'home' %}


{% block body %}
	<section class='news'>
		<h2 class='little-title'>Actualité</h2>
		{% for news in news %}
			<p>{{ news.content }}</p>
		{% endfor %}
	</section>
	<section id='home'>
		<h2 class='litle_title'>L’amap est plus qu’un “panier” !</h2>
		<ul class="btn-list">
			<li>
				<a href="https://www.helloasso.com/associations/retourn-amap/adhesions/adhesion-annuelle" target="_blank" class="btn">Adhérer à l'AMAP</a>
			</li>
		</ul>
		<ul class='card_list'>
			<li class='card'>
				<div class='card_head'>
					<div>
						<span>A</span>
						comme
						<span>Association</span>
					</div>
					<img src='{{asset('img/home/local.png')}}' alt='' aria-hidden='true'/>
				</div>
				<ul class='card_body'>
					<li>Présente depuis 2012 à Retournac.</li>
					<li>Permettre de rapprocher producteur et consommateur.</li>
					<li>Système reversant
						<strong>100% du montant du panier au paysan.</strong>
					</li>
				</ul>
			</li>
			<li class='card'>
				<div class='card_head'>
					<div>
						<span>M</span>
						comme
						<span>Maintien</span>
					</div>
					<img src='{{asset('img/home/protecting.png')}}' alt='' aria-hidden='true'/>
				</div>
				<ul class='card_body'>
					<li>Soutenir une agriculture de proximité, à taille humaine.</li>
					<li>Allier écologie, emploi agricole et pérennité des fermes.</li>
					<li>Rétablir le lien entre paysans et consommateurs.</li>
				</ul>
			</li>
			<li class='card'>
				<div class='card_head'>
					<div>
						<span>A</span>
						comme
						<span>Agriculture</span>
					</div>
					<img src='{{asset('img/home/planting.png')}}' alt='' aria-hidden='true'/>
				</div>
				<ul class='card_body'>
					<li>Proposer une palette de produits locaux, frais et de saisons.</li>
					<li>S'engager pour fournir des produits issus de l'agriculture biologique.</li>
					<li>Légumes, pain, oeufs, viande, produits laitiers, confitures, plantes ...</li>
				</ul>
			</li>
			<li class='card'>
				<div class='card_head'>
					<div>
						<span>P</span>
						comme
						<span>Paysanne</span>
					</div>
					<img src='{{asset('img/home/harvest.png')}}' alt='' aria-hidden='true'/>
				</div>
				<ul class='card_body'>
					<li>
						Chaque amapien s’engage sur une saison.</li>
					<li>Le paysan a l’assurance d’être rémunéré et d’écouler sa production.</li>
					<li>Permettre de soutenir l’agriculture paysanne de notre région.</li>
				</ul>
			</li>
		</ul>
	</hr>
	<h2>Nos partenaires</h2>
	<ul class='flex-row'>
		<li>
			<a href='https://www.ville-retournac.fr/' target='_blank' title='Ville de Retournac' aria-label='Ville de Retournac'>
				<img src='{{asset('img/home/logo-ville-de-retournac.png')}}' alt='logo ville de Retournac'/>
			</a>
		</li>
		<li>
			<a href='https://amap-aura.org/' target='_blank' title='AMAP AURA' aria-label='AMAP AURA'>
				<img src='{{asset('img/home/amap-aura-logo.png')}}' alt='logo AMAP AURA'/>
			</a>
		</li>
		<li>
			<a href='https://www.fne-aura.org/haute-loire/' target='_blank' title='France Nature Environnement 43' aria-label='France Nature Environnement 43'>
				<img src='{{asset('img/home/logo-france-nature-environnement-43.png')}}' alt='logo France Nature Environnement 43'/>
			</a>
		</li>
	</ul>
</section>{% endblock %}

templates/pages/productors.html.twig
{% extends 'base.html.twig' %}

{% block title 'Retourn\'AMAP - producteurs' %}

{% set active = 'productors' %}

{% block body %}
	<section id='productors'>
		<h2>Les producteurs</h2>
		<ul>
		{% for productor in productors %}
			<li class='card'>
				<figure>
					<img class='productor_picture' src='img/producteurs/{{ productor.filename }}' alt='{{ productor.imageDescription }}'/>
				</figure>
				<div class='productor_card_body'>
					{% if productor.link != '#' %}
						<h6>
							<a href='{{ productor.link }}' title='Voir le site' target='_blank' rel='noopener' class='underline'>
								{{ productor.name }}
								<img src='{{ asset('img/arrow-up-right-from-square-solid.png') }}' alt='' aria-hidden='true'/>
							</a>
						</h6>
					{% else %}
						<h6>
							{{ productor.name }}
						</h6>
					{% endif %}
					{% for contract in productor.contracts %}
						<p>
							<strong>{{ contract.name }}</strong>
							<br/>{{ productor.delivery }}
							{% if contract.description %}
								<br/><p>{{ contract.description }}</p>
							{% endif %}
							{% if contract.fileName %}
								<br/><a href='/doc/contrats/{{ contract.fileName }}' target='_blank' rel='noopener' class='underline'>Voir le contrat</a>&nbsp;
							{% endif %}
						</p>
						{% if productor.label %}
							<img src='img/label/{{ productor.label }}' alt='{{ productor.label }}' class='mt-2'/>
						{% endif %}
						{% endfor %}
					</div>
				</li>
			{% endfor %}
		</ul>
	</section>
	{% endblock %}

templates/pages/status.html.twig
{% extends 'base.html.twig' %}

{% block title 'Retourn\'AMAP - statuts' %}

{% set active = 'status' %}

{% block body %}
	<section id='status'>
		<h2>Statuts associatifs</h2>
		<article>
			<h3>Article 1 : Fondement</h3>
			<p>Il est fondé entre les adhérents aux présents statuts une association régie par la loi du 1er juillet 1901 et le décret du 16 août 1901.</p>
			<h3>Article 2 : Nom</h3>
			<p>L’association prend le nom d’Association pour le Maintien d’une Agriculture Paysanne (déposé au Journal Officiel du 4.08.2003 par Alliance Provence)
				<strong>RetournAMAP</strong>
			</p>
			<h3>Article 3 : Objet</h3>
			<p>L’association a pour objet :</p>
			<ul>
				<li>Promouvoir une agriculture respectueuse de l’environnement, des ressources naturelles, des territoires et des hommes : une agriculture durable, socialement équitable et écologiquement saine.
				</li>
				<li>Contribuer à la mise en place d’une économie solidaire entre consommateurs et producteurs locaux pour favoriser le développement des productions de qualité reflétant la diversité de notre terroir et la variété des savoir-faire.</li>
				<li>Soutenir les agriculteurs biologiques de proximité ou désirant s’engager dans une production biologique (conversion) pas forcément labélisée ou certifiée.</li>
				<li>Permettre aux consommateurs de manger sainement dans le respect de l’environnement, à un prix juste pour le consommateur et rémunérateur pour le paysan, établi en coresponsabilité. L’association intervient dans l’organisation des relations entre les adhérents et les partenaires et la distribution des produits dans le cadre d’une gestion désintéressée. Elle ne participe pas à l’achat et la vente des denrées. Elle peut organiser tout type de manifestations en lien avec ses objectifs.</li>
			</ul>
			<p>L’association s’appuie sur les principes décrits par la Charte des AMAP en Rhône-Alpes.</p>
			<h3>Article 4 : Siège</h3>
			<p>Le siège social est fixé à l’adresse suivante : 7 avenue d'Artias, 43130 Retournac</p>
			<h3>Article 5 : Indépendance</h3>
			<p>L’association est indépendante de tout parti politique.</p>
			<h3>Article 6 : Membres actifs</h3>
			<p>Pour être membre actif de l’Association, il faut :</p>
			<ul>
				<li>Adhérer à l’objet des présents statuts, aux principes et engagements définis par le règlement intérieur</li>
				<li>Signer le contrat d’engagement avec le(s) producteur(s) pour une durée déterminée.</li>
				<li>S’acquitter de la cotisation destinée :</li>
				<ul>
					<li>à couvrir les frais de fonctionnement de l’AMAP</li>
					<li>adhérer à Haute-Loire Biologique par l’intermédiaire de l’AMAP</li>
				</ul>
			</ul>
			<h3>Article 7 : Membres bienfaiteurs</h3>
			<p>Pour être membre bienfaiteur de l’Association, il faut :</p>
			<ul>
				<li>Adhérer à l’objet des présents statuts.</li>
				<li>S’acquitter de la cotisation.</li>
			</ul>
			<h3>Article 8 – Radiation</h3>
			<p>Pour non-paiement de la cotisation ou de l’abonnement, ou pour motif grave.</p>
			<h3>Article 9 – Ressources</h3>
			<p>Les ressources de l'association comprennent :</p>
			<ul>
				<li>le montant des cotisations et toutes formes de ressources non contraires à la loi</li>
				<li>les subventions, les dons</li>
			</ul>
			<h3>Article 10 – Conseil d'Administration</h3>
			<p>Le Conseil d’Administration est composé au minimum de 3 membres élus en Assemblée Générale :</p>
			<ul>
				<li>Président,</li>
				<li>Secrétaire,</li>
				<li>Trésorier,</li>
				<li>Et d'éventuels adjoints et suppléants.</li>
			</ul>
			<h3>Article 11– Réunion du Conseil d'Administration</h3>
			<p>Le Conseil d’Administration se réunit au moins 2 fois par an sur convocation du Président ou à la demande motivée d’un de ses membres.<br>Tout membre du conseil qui, sans excuse, n'aura pas assisté à 2 réunions consécutives, sera considéré comme démissionnaire.</p>
			<h3>Article 12– Assemblée générale ordinaire</h3>
			<p>L'assemblée générale ordinaire comprend tous les membres de l'association à jour de cotisation.<br>
				L'assemblée générale ordinaire se réunit chaque année.<br>
				Les membres de l'association sont convoqués 15 jours au moins avant la date fixée.<br>
				L'ordre du jour est indiqué sur les convocations.<br>
				L’AG procède au renouvellement, par tiers, des membres du Conseil d’Administration.<br>
			</p>
			<h3>Article 13- Assemblée générale extraordinaire</h3>
			<p>Une Assemblée générale extraordinaire peut être convoquée :</p>
			<ul>
				<li>par le Président en accord avec le Conseil d’Administration,</li>
				<li>ou à la demande d’au moins un tiers des membres à jour de leur cotisation, suivant les formalités prévues par l'article 12</li>
			</ul>
			<h3>Article 14 - Votes et décisions</h3>
			<p>Pour tous les votes du CA, et des Assemblées Générales ordinaires ou extraordinaires les décisions prises sont adoptées :<br>
				Sans conditions de quorum et à la majorité simple des membres présents ou représentés.<br>
				Dans le cas où cette majorité ne se dégagerait pas, la proposition mise au vote devra être revue et amendée et soumise à un nouveau vote.<br>
				Les pouvoirs ne sont valables, ainsi que les votes, que pour les membres à jour de cotisations (maximum 2 pouvoirs par personne).<br>
				Les décisions votées sont exécutoires immédiatement.
			</p>
			<h3>Article 15– Règlement intérieur</h3>
			<p>Un règlement intérieur peut être établi ultérieurement par le Conseil d’administration et présenté à l’Assemblée générale la plus proche.<br>
				Ce règlement est destiné à fixer les divers points non prévus par les statuts, notamment ceux qui ont trait au fonctionnement de l'association.
			</p>
			<h3>Article 16– Dissolution</h3>
			<p>La dissolution peut être prononcée conformément à l'article 9 de la loi du 1er juillet 1901 et au décret du 16 août 1901.Article 11.</p>
		</article>
		<span>Guillaume Charmasson - Président</span>
	</section>
{% endblock %}